### ISSUE TITLE
rrdtool-1.2.19 wont build on OpenBSD 4.0/i386

### ISSUE THREAD

**Issue by oetiker** [oetiker/rrdtool-1.x#82]
Cant get this to build.

Configure seems to work, when i attempt either a gmake or make, ater a couple of minutes int othe compile I get this:
# 

creating librrd_th.la
(cd .libs && rm -f librrd_th.la && ln -s ../librrd_th.la librrd_th.la)
/bin/sh ../libtool --tag=CC --mode=link gcc  -g -O2 -fno-strict-aliasing -Wall -std=gnu99 -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline -W  -fPIC -DPIC  -L/usr/lib -L/usr/local/lib     -L/usr/local/lib     -L/usr/X11R6/lib     -o rrdtool   librrd.la
gcc -g -O2 -fno-strict-aliasing -Wall -std=gnu99 -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wmissing-prototypes -Wmissing-declarations -Wnested-externs -Winline -W -fPIC -DPIC -o .libs/rrdtool  -L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib -L./.libs -lrrd -lart_lgpl_2 -lpng -lz -lm -lfreetype -Wl,-rpath,/usr/local/rrdtool-1.2.19/lib -Wl,-rpath,/usr/local/lib
/usr/local/lib/librrd.so.0.0: warning: strcpy() is almost always misused, please use strlcpy()
/usr/local/lib/librrd.so.0.0: warning: sprintf() is often misused, please use snprintf()
/usr/local/lib/librrd.so.0.0: warning: strcat() is almost always misused, please use strlcat()
/usr/lib/crt0.o(.text+0xa4): In function `___start':
: undefined reference to`main'
collect2: ld returned 1 exit status
gmake[2]: **\* [rrdtool] Error 1
gmake[2]: Leaving directory `/usr/home/alex/downloads/rrdtool-1.2.19/src'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory`/usr/home/alex/downloads/rrdtool-1.2.19'
gmake: **\* [all] Error 2

How do I fix it
